services:
  product_service:
    build:
      context: ./product_service
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./product_service:/usr/src/app
      - ./product_service/node_modules:/usr/src/app/node_modules:ro
    ports:
      - "8081:80"
    environment:
      - NODE_ENV=development
    command: npm run start:dev
    user: node
  order_service:
    build:
      context: ./order_service
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./order_service:/usr/src/app
      - ./order_service/node_modules:/usr/src/app/node_modules:ro
    ports:
      - "8082:80"
    environment:
      - NODE_ENV=development
    command: npm run start:dev
    user: node

  inventory_service:
    build:
      context: ./inventory_service
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./inventory_service:/usr/src/app
      - ./inventory_service/node_modules:/usr/src/app/node_modules:ro
    ports:
      - "8083:80"
    environment:
      - NODE_ENV=development
    command: npm run start:dev
    user: node
